stages:
  - test

lint:
  image: python:3.12
  stage: test
  before_script:
    - python -m pip install --upgrade pip
    - python -m pip install flake8
    - pip install -e ".[dev]"
  script:
    - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - flake8 . --per-file-ignores="__init__.py:F401" --count --exit-zero --max-complexity=10 --max-line-length=150 --statistics

test:
  image: python:3.12
  stage: test
  before_script:
    - python -m pip install --upgrade pip
    - python -m pip install pytest pytest-cov
    - pip install -e ".[dev]"
  script:
    - pytest tests/*.py